# tasks file for nodejs
- name: Download node 11 script
  shell: "curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -"

- name: Installing node
  yum:
    # enablerepo: epel
    state: present
    name:
      - nodejs
#- name: Installing npm
#  yum:
#    enablerepo: epel
#    state: present
#    name:
#      - npm
