# tasks file for nodejs

- name: Installing node
  yum:
    # enablerepo: epel
    state: present
    releasever: 11.1.0
    name:
      - nodejs

- name: Installing npm
  yum:
    enablerepo: epel
    state: latest
    name:
      - npm
